# Generated by Django 3.0.6 on 2020-05-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='product_images',
        ),
    ]
